name: Release AppImage

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-updates-job:
    runs-on: ubuntu-latest

    outputs:
      updated: ${{ steps.check-updates.outputs.updated }}
      appimagetag: ${{ steps.check-updates.outputs.appimagetag }}

    steps:
      - name: Set up param
        id: param
        run: awk -F/ '{print"owner="$1"\nrepo="$2}' <<< "${{ github.repository }}" >> "$GITHUB_OUTPUT"

      - name: Get latest tags
        id: latest-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ steps.param.outputs.owner }}
          repo: ${{ steps.param.outputs.repo }}
          query: |
            query($owner:String!,$repo:String!) {
              appimage: repository(owner:$owner, name:$repo) {
                refs(refPrefix:"refs/tags/", last:1) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
              vim: repository(owner:"vim", name:"vim") {
                refs(refPrefix:"refs/tags/", last:1) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }
          jq_extract: >+
            "vim_tag=" + .data.vim.refs.edges[0].node.name,
            "appimage_tag=" + .data.appimage.refs.edges[0].node.name
        run: |
          gh api graphql -F owner="$owner" -F repo="$repo" -f query="$query" --jq "$jq_extract" | \
            tee -a "$GITHUB_ENV"

      - name: Check updates
        id: check-updates
        run: |
          printf >> "$GITHUB_OUTPUT" '%s\n' \
           "appimagetag=${appimage_tag}" \
           "updated=$([[ ${appimage_tag} != ${vim_tag} ]] && echo true)"

  create-appimage-job:
    runs-on: ubuntu-22.04

    needs: check-updates-job

    if: needs.check-updates-job.outputs.updated == 'true'

    env:
      VIM_REF: ${{ needs.check-updates-job.outputs.appimagetag }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build and run Docker container
        run: |
          cat <<EOF > Dockerfile
          FROM ubuntu:18.04

          ENV DEBIAN_FRONTEND=noninteractive
          ENV DISPLAY=:99
          ENV TERM=xterm
          ENV CC=gcc

          # Install dependencies
          RUN apt-get update && apt-get install -y \
              autoconf \
              automake \
              lcov \
              gettext \
              libcanberra-dev \
              libperl-dev \
              python2-dev \
              python3-dev \
              liblua5.3-dev \
              lua5.3 \
              ruby-dev \
              tcl-dev \
              cscope \
              libgtk-3-dev \
              desktop-file-utils \
              libtool-bin \
              at-spi2-core \
              libsodium-dev \
              gcc-10 \
              g++-10 \
              make \
              git \
              xvfb \
              wget \
              sudo \
              sysvinit-utils \
              && rm -rf /var/lib/apt/lists/*

          # Set up GCC-10 as default
          RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
              && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

          WORKDIR /workspace
          COPY . .

          # Set up environment
          RUN sysctl -w net.ipv6.conf.lo.disable_ipv6=0
          RUN bash vim/ci/setup-xvfb.sh

          # Build Vim
          RUN bash scripts/build_vim.sh

          # Test Vim
          RUN (cd vim/src/gvim && make test) || bash scripts/dump_failed_screentests.sh

          # Create AppImages
          RUN bash -e scripts/appimage.sh GVim
          RUN bash -e scripts/appimage.sh Vim
          EOF

          sudo docker build -t vim-appimage-builder .
          sudo docker run --rm -v $(pwd):/output vim-appimage-builder sh -c "cp *.AppImage *.zsync /output/"

      - name: Verify AppImages
        run: |
          ls -lh *.AppImage
          ./Vim*.AppImage --version
          ./GVim*.AppImage --version

      - name: Commit and push
        id: commit
        run: |
          tag_name=$(git -C vim describe --tags --abbrev=0)
          echo "tag_name=${tag_name}" >> "$GITHUB_OUTPUT"
          vim_summary=$(git submodule summary vim)
          workflow_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}

          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git commit -m "Vim: ${tag_name}" -m "${vim_summary}" -m "${workflow_url}" vim
          git tag -f "${tag_name}" -m "Vim: ${tag_name}"
          git push --follow-tags -u origin "${GITHUB_REF_NAME}"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.commit.outputs.tag_name }}
        run: |
          gh release create "$tag_name" \
            *.AppImage *.zsync \
            -F release.body -t "Vim: $tag_name"
